[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    login: Login module tests
    new_customer: New Customer module tests
    deposit: Deposit module tests
